### PR TITLE
Cleanup before starting native (Linux) LV2 plugin

### PR DESCRIPTION
**Pull request by dcoredump**
Ok.

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
@asb2m10 @dcoredump Apart from a rebase, what's needed to get this merged?
Asking because I'd really like the possibility of an LV2 version of dexed :)

**Comment by dcoredump** [comment]
Hi Simon,

I think this is not an easy task. I stripped of the JUCE code and the
GUI and wrote an own run() method for LVTK. With a lot of #ifdefs you
might getting it working - but this won't be nice code :-(

The other way is to use an JUCE-LV2-wrapper, like FalkTX has done in his
DISTRHO compilation. For me this was not an option because I wanted to
have a raw sound plugin without GUI but with SYSEX compatible
LV2-parameters. I am using Dexed inside MOD-UI
(https://github.com/moddevices/mod-ui or http://moddevices.com/) and it
fits perfectly.

Regards, Holger

**Comment by SpotlightKid** [comment]
It would be very cool, if this would eventually lead to an official LV2 version of Dexed!

**Comment by Jacalz** [comment]
An LV2 version of this would be really cool! Any news on this?

**Comment by dcoredump** [comment]
There is a LV2 version: https://github.com/dcoredump/dexed/tree/native-lv2

I put everything into a branch named "native-lv2"

Regards, Holger

**Comment by Jacalz** [comment]
> There is a LV2 version: https://github.com/dcoredump/dexed/tree/native-lv2
> 
> I put everything into a branch named "native-lv2"
> 
> Regards, Holger

Thanks, that sounds great 👍 Would be great to see this merged 🙂

**Comment by dcoredump** [comment]
> > There is a LV2 version: https://github.com/dcoredump/dexed/tree/native-lv2
> > I put everything into a branch named "native-lv2"
> > Regards, Holger
> 
> Thanks, that sounds great +1 Would be great to see this merged slightly_smiling_face

Hm, there is  so much changed in the LV" version, so a merge is not really practicable.

Forgot to mention that the native-lv2 version is created especially for using on MOD-UI (MOD-Duo or Zynthian), so the complete GUI is dropped.

**Comment by dcoredump** [comment]
I created this pull-request incorrectly and therefore close it.

An LV2 version (without GUI!) for use in https://github.com/moddevices/mod-ui or via jalv can be found at https://github.com/dcoredump/dexed/tree/native-lv2 .

**Pull request closed without merging**
