### PR TITLE
Add MTS-ESP support

### PR DESCRIPTION
**Pull request by olicash**
For more info on MTS-ESP see https://oddsound.com/usingmtsesp.php and https://github.com/ODDSound/MTS-ESP.

MTS-ESP has been implemented in a number of synths already, including Surge, with which baconpaul was very helpful.  The implementation here in Dexed lets the SST tuning library take precedence, so if a user explicitly loads a .scl file it will use that.  If none is loaded it will follow the tuning from an MTS-ESP master plug-in instanced in the same session or, if there is none, automatically fall back to 12-TET.  All this is very low compute cost, so no overhead to worry about.

For any queries feel free to get in touch at info@odddound.com.

### CODE REVIEW

**Comment by tank-trax** [comment]
as I am sure you already know MTS-ESP is now working in Entonal Studio in Linux... I've tested OB-XD and Surge XT (built locally on Debian 11 using the updated MTS-ESP submodule) and they both loaded

upon success I inquired about Dexed and @baconpaul pointed me to this branch.... I've built it and can confirm that  Dexed is also recognized

here is an example in Bitwig 4.1.6 on Debian 11

image

I noticed that your branch is 36 commits ahead and 22 commits behind asb2m10's Dexed master branch and hasn't been merged yet, possibly due to its using a jucer file whereas asb2m10's Dexed master branch is using cmake

baconpaul suggested that I ask you to bring your branch to head in cmake

once the PR is up to date he said he would happily endorse its getting merged

thanks!!

**Comment by asb2m10** [comment]
Hi @tank-trax, it was planned that I merged MTS-ESP in the next Dexed version but the original pull request was using projucer build without being properly updated, it is the reason I didn't merge it.

Now with cmake (opposed to projucer), it will clean things up. I'll see what I can do.

**Comment by olicash** [comment]
Thanks for pulling!  I've make a note to look at adding Cmake to the MTS-ESP repo.

**Comment by tank-trax** [comment]
I built the latest build of Dexed from asb2m10's repo and it works with Entonal Studio's MTS-ESP setting

thanks!!!!

**Pull request merged**
